spring:
  application:
    name: zuul-server
server:
  port: 8083

zuul:
  routes:
    products:
      path: /products/**
      serviceId: service-provider


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8631/eureka