spring:
  application:
    name: zuul-server
server:
  port: 8083

zuul:
  host:
    connect-timeout-millis: 2000 # 为啥不存在
    max-total-connections: 200 # 最大连接数 限流  http连接池大小
    max-per-route-connections: 20 # 每个host最大连接数
  ribbon-isolation-strategy: semaphore #
  semaphore:
    max-semaphores: 100
  routes: # 路由代理
    products:
      path: /products/**
      serviceId: service-provider
    product2:
      path: /wsl/*
      url: http://localhost:8001

# 注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8631/eureka