spring:
  redis:
    database: 0
    host: 120.79.158.143
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
    timeout: 1000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    # 打开发布确认
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true