spring:
  redis:
    database: 0
    host: 120.79.158.143
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
    timeout: 1000
    rabbitmq:
      host: 10.216.32.225
      port: 15672
      username: guest
      password: guest
      #发送确认 对应RabbitTemplate.ConfirmCallback接口
#      publisher-confirms: true
      #发送失败回退，对应RabbitTemplate.ReturnCallback接口
      publisher-returns: true
#      在配置文件中的话 全局的ack模式都会生效 可以手动注册相关容器SimpleMessageListenerContainer 来实现单个消费者的ack
#      listener:
#        direct:
#          acknowledge-mode: manual
#        simple:
#          acknowledge-mode: manual
server:
  port: 9090