spring:
  application:
    name: config-server
  redis:
    database: 0
    host: 120.79.158.143
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
    timeout: 1000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
  cloud:
    config:
      server:
        git:
          url: https://github.com/songlinwang/gateway
          username: songlinwang
          password: 123456

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
